title: 代理服务器网
description:  A beautiful template for your CV.
url: https://www.dailifuwuqi.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
